# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
- group: CertPassword
- name: CertPassword
  
jobs:
- job: Build
  pool:
    name: Hosted Windows 2019 with VS2019
    demands: msbuild

  steps:
  - task: MSBuild@1
    displayName: Build for Release
    inputs:
      platform: Any CPU
      solution: src/PresenceLight.sln
      msbuildArguments: /restore 
      configuration: Release
      maximumCpuCount: false

